### PR TITLE
#24 Test#1 using DataProvider

### LINKED ISSUE #24: Test #18,19,20,21
Create Automated test using DataProvider: 
Test#18: Новый комментарий может состоять из латинских букв
Test#19: Новый комментарий может состоять из кирилических букв
Test#20: Новый комментарий может состоять из цифренного значения
Test#21: Новый комментарий может вмещать в себе буквенные символы с верхним подчеркиванием

### PR DESCRIPTION
**Pull request by oteplova**
Test#1: create new comment using DataProvider. 
It covers following tests: 
  #18: new comment can be created with comment text which consists of Latin characters;
  #19: new comment can be created with comments text which consists of Cyrillic characters; 
  #20: new comment can be created with comments text which consists of numbers;
  #21: new comment can be created with comments text which consists of alphabetic characters with underscore.  

Closes #24

### CODE REVIEW

**Comment by oteplova** [comment]
@extsoft  please  check.

**Comment by extsoft** [comment]
@oteplova please fix the conflicts.

**Comment by oteplova** [comment]
@extsoft I've resolved the conflicts. Please check.

**Comment by extsoft** [comment]
@oteplova please resolve conflicts again as the master branch was updated.

**Comment by oteplova** [comment]
@extsoft  I've resolved conflicts. Please check.

**Review by extsoft — APPROVED** [review]
@oteplova assertion algorithm can be better.

**Pull request merged**
